# Generated by Django 3.1.3 on 2021-06-17 23:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('event_time', models.DateTimeField()),
                ('event_type', models.IntegerField(choices=[(1, 'Івент потоку "Слово"'), (2, 'Івент потоку "Діло"')])),
                ('title', models.CharField(max_length=256)),
                ('organizers', models.CharField(max_length=256)),
                ('description', models.TextField(blank=True, null=True)),
                ('maximal_participants', models.IntegerField()),
                ('event_lane', models.IntegerField(blank=True, choices=[(1, 'Івент потоку "Слово"'), (2, 'Івент потоку "Діло"')], null=True)),
                ('finished_notification', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EventRegistration',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('registration_status', models.IntegerField(choices=[(1, 'У черзі'), (2, 'Участь попередньо підтверджено'), (3, 'Участь підтверджено'), (4, 'Участь відхилено'), (5, 'Не допущено за проханням організатора')], default=1)),
                ('_times_asked', models.IntegerField(default=0)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registered_users', to='scheduler.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registered_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
