# Generated by Django 3.1.3 on 2021-07-16 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ('event_time',)},
        ),
        migrations.AlterModelOptions(
            name='eventregistration',
            options={'ordering': ('created',)},
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='_was_invited',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_lane',
            field=models.IntegerField(blank=True, choices=[(1, 'Перший потік'), (2, 'Другий потік')], null=True),
        ),
    ]
