# Generated by Django 3.1.3 on 2021-07-20 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_auto_20210716_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_lane',
            field=models.IntegerField(blank=True, choices=[(1, 'Великий'), (2, 'Малий')], null=True),
        ),
    ]
