# Generated by Django 3.1.3 on 2021-07-29 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0003_auto_20210720_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='night_event_lane',
            field=models.IntegerField(blank=True, choices=[(1, 'Великий'), (2, 'Party Room: Cuddle-puddle'), (3, 'Party Room: Карти, гроші, два стволи'), (4, 'Party Room: CYBERPUNK#TRAP'), (5, 'Організаторське приміщення')], null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.IntegerField(choices=[(1, 'Івент потоку "Слово"'), (2, 'Івент потоку "Діло"'), (3, 'Івент Do!Roleplay Night')]),
        ),
    ]
