# Generated by Django 3.1.3 on 2021-07-29 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0004_auto_20210729_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='night_event_lane',
            field=models.IntegerField(blank=True, choices=[(1, 'Велика зала: танці та бар'), (2, 'Party Room: Cuddle-puddle'), (3, 'Party Room: Карти, гроші, два стволи'), (4, 'Party Room: CYBERPUNK#TRAP'), (5, 'Організаторське приміщення')], null=True),
        ),
    ]
