# Generated by Django 3.1.3 on 2021-07-31 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0005_auto_20210729_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventregistration',
            name='invite_finished',
            field=models.BooleanField(default=False),
        ),
    ]
