# Generated by Django 3.1.3 on 2021-06-17 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='ticket_id',
        ),
        migrations.AddField(
            model_name='useraccount',
            name='is_tengro',
            field=models.BooleanField(default=False, help_text="Designates if it's superduper admin.", verbose_name='staff status'),
        ),
    ]
